import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function App({ Component, pageProps }) {
  // localhost:3000/login -> _document.js -> _app.js -> Component (Login.jsx)
  // localhost:3000/ -> _document.js -> _app.js -> Component (index.js)
  const router = useRouter()

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sialogo.ico" />
      </Head>
      {
        router.route !== '/login' ? (
          <Navbar />
        ) : (
          <></>
        )
      }

      <Component {...pageProps} />
    </>
  )
}
